name: Deploy to heroku

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: |
          npm ci
          npm install -g https://github.com/swagger-api/swagger-node 
          
      - name: Install heroku-cli
        run: curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          
      - name: Run tests
        run: npm test
        
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tecdottir"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
