name: Update tecdottir database

on:
  schedule:
    - cron:  '14/15 * * * *' # runs daily
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    environment: production

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get install sqlite3
        
    - name: Update database
      run: python update_database.py
