name: Update tecdottir database

on:
  schedule:
    - cron:  '14/15 * * * *' # runs daily
  workflow_dispatch:

jobs:
  update_data:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    environment: production

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - uses: akhileshns/heroku-deploy@v3.6.8
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_email: ${{secrets.HEROKU_EMAIL}}
        justlogin: true
        
    - name: Get DATABASE_URL
      id: db
      run: |
        heroku ps -a tecdottir
        echo "::set-output name=db_url::$(heroku config:get DATABASE_URL -a tecdottir)"
      
    - name: Download CSVs
      run: ./download_csvs.sh
      
    - name: Update database
      env:
        DATABASE_URL: ${{steps.db.outputs.db_url}}
      run: |
        python update_database.py -f messwerte_mythenquai_2022.csv -t mythenquai --purge
        #python update_database.py -f messwerte_mythenquai_2007-2021.csv -t mythenquai 
        python update_database.py -f messwerte_tiefenbrunnen_2022.csv -t tiefenbrunnen --purge
        #python update_database.py -f messwerte_tiefenbrunnen_2007-2021.csv -t tiefenbrunnen
